# all directories in this file are located relative to the project root

[qroma.project]
id = "qroma-lights-2"
name = "qroma-lights-2"
# use semantic versioning - see https://en.wikipedia.org/wiki/Software_versioning [Semantic versioning]
version = "0.1.0"


[qroma.project.dirs]
pb_root = "C:/Users/ajb/qroma-projects/qroma-lights-2/protobufs"
firmware_root = "C:/Users/ajb/qroma-projects/qroma-lights-2/firmware/esp32/qroma-lights-2"
app_root = "C:/Users/ajb/qroma-projects/qroma-lights-2/apps/py-qroma-io"
site_root = "C:/Users/ajb/qroma-projects/qroma-lights-2/sites/site-www-qroma-lights-2"


[qroma.project.firmware]
platforms = [
  "platformio",
]


[qroma.project.run.commands.firmware.platformio]
build = "run"
install = "run --target upload --environment esp32dev"
monitor = ""

[qroma.project.stages.sw.protobuf]
root_dir = "C:/Users/ajb/qroma-projects/qroma-lights-2/protobufs/protobufs"
compilers = [
  "nanopb",
  "python",
  "typescript",
  "dart",
]

[[qroma.project.stages.sw.protobuf.sources]]
source_path = "C:/Users/ajb/qroma-projects/qroma-lights-2/protobufs/protofiles-in"
dest_path = "C:/Users/ajb/qroma-projects/qroma-lights-2/protobufs/protofiles-out"


[qroma.project.stages.sw.protobuf.replication]
nanopb.dirs = ["C:/Users/ajb/qroma-projects/qroma-lights-2/firmware/esp32/qroma-lights-2/src/qroma-proto", ]
python.dirs = ["C:/Users/ajb/qroma-projects/qroma-lights-2/apps/py-qroma-io/qroma_proto", ]
typescript.dirs = ["C:/Users/ajb/qroma-projects/qroma-lights-2/sites/site-www-qroma-lights-2/src/qroma-proto", ]
dart.dirs = []


[qroma.project.stages.sw.firmware]
project_dirs = []


[qroma.project.stages.sw.apps]
project_dirs = []


[qroma.project.stages.sw.sites]
project_dirs = []


[qroma.project.stages.sw.sites.bundle]
local_bundle_static_dir="C:/Users/ajb/qroma-projects/qroma-lights-2/sites/site-www-qroma-lights-2/static"
local_bundle_static_qroma_dir="C:/Users/ajb/qroma-projects/qroma-lights-2/sites/site-www-qroma-lights-2/static/qroma"
local_bundle_version_content_root_dir="C:/Users/ajb/qroma-projects/qroma-lights-2/sites/site-www-qroma-lights-2/static/qroma/versions"
hosted_qroma_bundle_root="/qroma"
hosted_qroma_bundle_versions_root="/qroma/versions"
hosted_bundle_version_path="/qroma/versions/0.1.0"


[[qroma.project.stages.sw.sites.bundle.publish_version.firmware_file_replications]]
source_filepath="C:/Users/ajb/qroma-projects/qroma-lights-2/firmware/esp32/qroma-lights-2/.pio/build/esp32dev/firmware.bin"
local_publication_filepath="C:/Users/ajb/qroma-projects/qroma-lights-2/sites/site-www-qroma-lights-2/static/qroma/versions/0.1.0/firmware/firmware.bin"
hosted_publication_filepath="/qroma/versions/0.1.0/firmware/firmware.bin"


[[qroma.project.stages.sw.sites.bundle.publish_version.firmware_file_replications]]
source_filepath="C:/Users/ajb/qroma-projects/qroma-lights-2/firmware/esp32/qroma-lights-2/.pio/build/esp32dev/bootloader.bin"
local_publication_filepath="C:/Users/ajb/qroma-projects/qroma-lights-2/sites/site-www-qroma-lights-2/static/qroma/versions/0.1.0/firmware/bootloader.bin"
hosted_publication_filepath="/qroma/versions/0.1.0/firmware/bootloader.bin"


[[qroma.project.stages.sw.sites.bundle.publish_version.firmware_file_replications]]
source_filepath="C:/Users/ajb/qroma-projects/qroma-lights-2/firmware/esp32/qroma-lights-2/.pio/build/esp32dev/partitions.bin"
local_publication_filepath="C:/Users/ajb/qroma-projects/qroma-lights-2/sites/site-www-qroma-lights-2/static/qroma/versions/0.1.0/firmware/partitions.bin"
hosted_publication_filepath="/qroma/versions/0.1.0/firmware/partitions.bin"


[[qroma.project.stages.sw.sites.bundle.publish_version.firmware_file_replications]]
source_filepath="C:/Users/ajb/.platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin"
local_publication_filepath="C:/Users/ajb/qroma-projects/qroma-lights-2/sites/site-www-qroma-lights-2/static/qroma/versions/0.1.0/firmware/boot_app0.bin"
hosted_publication_filepath="/qroma/versions/0.1.0/firmware/boot_app0.bin"


[[qroma.project.stages.sw.sites.bundle.publish_version.zipped_dirs]]
source_dir="C:/Users/ajb/qroma-projects/qroma-lights-2/protobufs/protofiles-out"
local_publication_zip_file="C:/Users/ajb/qroma-projects/qroma-lights-2/sites/site-www-qroma-lights-2/static/qroma/versions/0.1.0/protobufs.zip"


[[qroma.project.stages.sw.sites.bundle.publish_version.generated_files]]
local_publication_filepath="C:/Users/ajb/qroma-projects/qroma-lights-2/sites/site-www-qroma-lights-2/static/qroma/versions/0.1.0/firmware/manifest-firmware.json"
hosted_publication_filepath="/qroma/versions/0.1.0/firmware/manifest-firmware.json"
template_str="""{
  "name": "qroma-lights-2",
  "version": "esp32",
  "builds": [
    {
      "chipFamily": "ESP32",
      "parts": [
        { "path": "bootloader.bin", "offset": 4096 },
        { "path": "partitions.bin", "offset": 32768 },
        { "path": "boot_app0.bin", "offset": 57344 },
        { "path": "firmware.bin", "offset": 65536 }
      ]
    }
  ]
}
"""