/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "hello-qroma.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(HelloQromaRequest, HelloQromaRequest, AUTO)


PB_BIND(HelloQromaResponse, HelloQromaResponse, AUTO)


PB_BIND(MathRequest, MathRequest, AUTO)


PB_BIND(MathResult_Add, MathResult_Add, AUTO)


PB_BIND(MathResult_Subtract, MathResult_Subtract, AUTO)


PB_BIND(MathResult_AddAndSubtract, MathResult_AddAndSubtract, AUTO)


PB_BIND(MathResponse, MathResponse, AUTO)


PB_BIND(SetUpdateConfiguration, SetUpdateConfiguration, AUTO)


PB_BIND(SetUpdateConfigurationResponse, SetUpdateConfigurationResponse, AUTO)


PB_BIND(SetUpdateProgressIndicator, SetUpdateProgressIndicator, AUTO)


PB_BIND(SetUpdateProgressIndicatorResponse, SetUpdateProgressIndicatorResponse, AUTO)


PB_BIND(UptimeUpdateResponse, UptimeUpdateResponse, AUTO)


PB_BIND(ProgressIndicatorUpdateResponse, ProgressIndicatorUpdateResponse, AUTO)


PB_BIND(UpdateResponse, UpdateResponse, AUTO)


PB_BIND(PingRequest, PingRequest, AUTO)


PB_BIND(PingResponse, PingResponse, AUTO)


PB_BIND(MyAppCommand, MyAppCommand, AUTO)


PB_BIND(MyAppResponse, MyAppResponse, AUTO)





