/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_HELLO_QROMA_PB_H_INCLUDED
#define PB_HELLO_QROMA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _MathOperation { 
    MathOperation_MathOp_NotSet = 0, 
    MathOperation_MathOp_Add = 1, 
    MathOperation_MathOp_Subtract = 2, 
    MathOperation_MathOp_Add_And_Subtract = 3 
} MathOperation;

typedef enum _UpdateType { 
    UpdateType_UpdateType_NotSet = 0, 
    UpdateType_UpdateType_None = 1, 
    UpdateType_UpdateType_Interval = 2, 
    UpdateType_UpdateType_ProgressIndicator = 3 
} UpdateType;

/* Struct definitions */
typedef struct _HelloQromaRequest { 
    char name[20]; 
} HelloQromaRequest;

typedef struct _HelloQromaResponse { 
    char response[20]; 
    uint32_t callCount; 
    uint32_t nameLength; 
} HelloQromaResponse;

typedef struct _MathRequest { 
    uint32_t a; 
    uint32_t b; 
    MathOperation op; 
} MathRequest;

typedef struct _MathResult_Add { 
    uint32_t result; 
} MathResult_Add;

typedef struct _MathResult_AddAndSubtract { 
    uint32_t addResult; 
    uint32_t subtractResult; 
} MathResult_AddAndSubtract;

typedef struct _MathResult_Subtract { 
    uint32_t result; 
} MathResult_Subtract;

typedef struct _PingRequest { 
    uint32_t pingId; 
} PingRequest;

typedef struct _PingResponse { 
    uint32_t pingId; 
    uint32_t uptime; 
} PingResponse;

typedef struct _ProgressIndicatorUpdateResponse { 
    char progressIndicator[50]; 
} ProgressIndicatorUpdateResponse;

typedef struct _SetUpdateConfiguration { 
    UpdateType updateType; 
    uint32_t updateIntervalInMs; 
} SetUpdateConfiguration;

typedef struct _SetUpdateConfigurationResponse { 
    bool success; 
} SetUpdateConfigurationResponse;

typedef struct _SetUpdateProgressIndicator { 
    char indicatorChars[5]; 
} SetUpdateProgressIndicator;

typedef struct _SetUpdateProgressIndicatorResponse { 
    bool success; 
    char statusMessage[100]; 
} SetUpdateProgressIndicatorResponse;

typedef struct _UptimeUpdateResponse { 
    uint32_t uptime; 
} UptimeUpdateResponse;

typedef struct _MathResponse { 
    pb_size_t which_response;
    union {
        MathResult_Add addResult;
        MathResult_Subtract subtractResult;
        MathResult_AddAndSubtract addAndSubtractResult;
    } response; 
} MathResponse;

typedef struct _MyAppCommand { 
    pb_size_t which_command;
    union {
        HelloQromaRequest helloQromaRequest;
        MathRequest mathRequest;
        SetUpdateConfiguration setUpdateConfiguration;
        SetUpdateProgressIndicator setUpdateProgressIndicator;
        PingRequest pingRequest;
    } command; 
} MyAppCommand;

typedef struct _UpdateResponse { 
    pb_size_t which_update;
    union {
        UptimeUpdateResponse uptimeUpdateResponse;
        ProgressIndicatorUpdateResponse progressIndicatorUpdateResponse;
    } update; 
} UpdateResponse;

typedef struct _MyAppResponse { 
    pb_size_t which_response;
    union {
        HelloQromaResponse helloQromaResponse;
        MathResponse mathResponse;
        SetUpdateConfigurationResponse setUpdateConfigurationResponse;
        SetUpdateProgressIndicatorResponse setUpdateProgressIndicatorResponse;
        PingResponse pingResponse;
        UpdateResponse update;
    } response; 
} MyAppResponse;


/* Helper constants for enums */
#define _MathOperation_MIN MathOperation_MathOp_NotSet
#define _MathOperation_MAX MathOperation_MathOp_Add_And_Subtract
#define _MathOperation_ARRAYSIZE ((MathOperation)(MathOperation_MathOp_Add_And_Subtract+1))

#define _UpdateType_MIN UpdateType_UpdateType_NotSet
#define _UpdateType_MAX UpdateType_UpdateType_ProgressIndicator
#define _UpdateType_ARRAYSIZE ((UpdateType)(UpdateType_UpdateType_ProgressIndicator+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define HelloQromaRequest_init_default           {""}
#define HelloQromaResponse_init_default          {"", 0, 0}
#define MathRequest_init_default                 {0, 0, _MathOperation_MIN}
#define MathResult_Add_init_default              {0}
#define MathResult_Subtract_init_default         {0}
#define MathResult_AddAndSubtract_init_default   {0, 0}
#define MathResponse_init_default                {0, {MathResult_Add_init_default}}
#define SetUpdateConfiguration_init_default      {_UpdateType_MIN, 0}
#define SetUpdateConfigurationResponse_init_default {0}
#define SetUpdateProgressIndicator_init_default  {""}
#define SetUpdateProgressIndicatorResponse_init_default {0, ""}
#define UptimeUpdateResponse_init_default        {0}
#define ProgressIndicatorUpdateResponse_init_default {""}
#define UpdateResponse_init_default              {0, {UptimeUpdateResponse_init_default}}
#define PingRequest_init_default                 {0}
#define PingResponse_init_default                {0, 0}
#define MyAppCommand_init_default                {0, {HelloQromaRequest_init_default}}
#define MyAppResponse_init_default               {0, {HelloQromaResponse_init_default}}
#define HelloQromaRequest_init_zero              {""}
#define HelloQromaResponse_init_zero             {"", 0, 0}
#define MathRequest_init_zero                    {0, 0, _MathOperation_MIN}
#define MathResult_Add_init_zero                 {0}
#define MathResult_Subtract_init_zero            {0}
#define MathResult_AddAndSubtract_init_zero      {0, 0}
#define MathResponse_init_zero                   {0, {MathResult_Add_init_zero}}
#define SetUpdateConfiguration_init_zero         {_UpdateType_MIN, 0}
#define SetUpdateConfigurationResponse_init_zero {0}
#define SetUpdateProgressIndicator_init_zero     {""}
#define SetUpdateProgressIndicatorResponse_init_zero {0, ""}
#define UptimeUpdateResponse_init_zero           {0}
#define ProgressIndicatorUpdateResponse_init_zero {""}
#define UpdateResponse_init_zero                 {0, {UptimeUpdateResponse_init_zero}}
#define PingRequest_init_zero                    {0}
#define PingResponse_init_zero                   {0, 0}
#define MyAppCommand_init_zero                   {0, {HelloQromaRequest_init_zero}}
#define MyAppResponse_init_zero                  {0, {HelloQromaResponse_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define HelloQromaRequest_name_tag               1
#define HelloQromaResponse_response_tag          1
#define HelloQromaResponse_callCount_tag         2
#define HelloQromaResponse_nameLength_tag        3
#define MathRequest_a_tag                        1
#define MathRequest_b_tag                        2
#define MathRequest_op_tag                       3
#define MathResult_Add_result_tag                1
#define MathResult_AddAndSubtract_addResult_tag  1
#define MathResult_AddAndSubtract_subtractResult_tag 2
#define MathResult_Subtract_result_tag           1
#define PingRequest_pingId_tag                   1
#define PingResponse_pingId_tag                  1
#define PingResponse_uptime_tag                  2
#define ProgressIndicatorUpdateResponse_progressIndicator_tag 1
#define SetUpdateConfiguration_updateType_tag    1
#define SetUpdateConfiguration_updateIntervalInMs_tag 2
#define SetUpdateConfigurationResponse_success_tag 1
#define SetUpdateProgressIndicator_indicatorChars_tag 1
#define SetUpdateProgressIndicatorResponse_success_tag 1
#define SetUpdateProgressIndicatorResponse_statusMessage_tag 2
#define UptimeUpdateResponse_uptime_tag          1
#define MathResponse_addResult_tag               1
#define MathResponse_subtractResult_tag          2
#define MathResponse_addAndSubtractResult_tag    3
#define MyAppCommand_helloQromaRequest_tag       1
#define MyAppCommand_mathRequest_tag             2
#define MyAppCommand_setUpdateConfiguration_tag  3
#define MyAppCommand_setUpdateProgressIndicator_tag 4
#define MyAppCommand_pingRequest_tag             5
#define UpdateResponse_uptimeUpdateResponse_tag  1
#define UpdateResponse_progressIndicatorUpdateResponse_tag 2
#define MyAppResponse_helloQromaResponse_tag     1
#define MyAppResponse_mathResponse_tag           2
#define MyAppResponse_setUpdateConfigurationResponse_tag 3
#define MyAppResponse_setUpdateProgressIndicatorResponse_tag 4
#define MyAppResponse_pingResponse_tag           5
#define MyAppResponse_update_tag                 6

/* Struct field encoding specification for nanopb */
#define HelloQromaRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              1)
#define HelloQromaRequest_CALLBACK NULL
#define HelloQromaRequest_DEFAULT NULL

#define HelloQromaResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   response,          1) \
X(a, STATIC,   SINGULAR, UINT32,   callCount,         2) \
X(a, STATIC,   SINGULAR, UINT32,   nameLength,        3)
#define HelloQromaResponse_CALLBACK NULL
#define HelloQromaResponse_DEFAULT NULL

#define MathRequest_FIELDLIST(X, a_) \
X(a_, STATIC,   SINGULAR, UINT32,   a,                 1) \
X(a_, STATIC,   SINGULAR, UINT32,   b,                 2) \
X(a_, STATIC,   SINGULAR, UENUM,    op,                3)
#define MathRequest_CALLBACK NULL
#define MathRequest_DEFAULT NULL

#define MathResult_Add_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   result,            1)
#define MathResult_Add_CALLBACK NULL
#define MathResult_Add_DEFAULT NULL

#define MathResult_Subtract_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   result,            1)
#define MathResult_Subtract_CALLBACK NULL
#define MathResult_Subtract_DEFAULT NULL

#define MathResult_AddAndSubtract_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   addResult,         1) \
X(a, STATIC,   SINGULAR, UINT32,   subtractResult,    2)
#define MathResult_AddAndSubtract_CALLBACK NULL
#define MathResult_AddAndSubtract_DEFAULT NULL

#define MathResponse_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,addResult,response.addResult),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,subtractResult,response.subtractResult),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,addAndSubtractResult,response.addAndSubtractResult),   3)
#define MathResponse_CALLBACK NULL
#define MathResponse_DEFAULT NULL
#define MathResponse_response_addResult_MSGTYPE MathResult_Add
#define MathResponse_response_subtractResult_MSGTYPE MathResult_Subtract
#define MathResponse_response_addAndSubtractResult_MSGTYPE MathResult_AddAndSubtract

#define SetUpdateConfiguration_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    updateType,        1) \
X(a, STATIC,   SINGULAR, UINT32,   updateIntervalInMs,   2)
#define SetUpdateConfiguration_CALLBACK NULL
#define SetUpdateConfiguration_DEFAULT NULL

#define SetUpdateConfigurationResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1)
#define SetUpdateConfigurationResponse_CALLBACK NULL
#define SetUpdateConfigurationResponse_DEFAULT NULL

#define SetUpdateProgressIndicator_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   indicatorChars,    1)
#define SetUpdateProgressIndicator_CALLBACK NULL
#define SetUpdateProgressIndicator_DEFAULT NULL

#define SetUpdateProgressIndicatorResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, STATIC,   SINGULAR, STRING,   statusMessage,     2)
#define SetUpdateProgressIndicatorResponse_CALLBACK NULL
#define SetUpdateProgressIndicatorResponse_DEFAULT NULL

#define UptimeUpdateResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   uptime,            1)
#define UptimeUpdateResponse_CALLBACK NULL
#define UptimeUpdateResponse_DEFAULT NULL

#define ProgressIndicatorUpdateResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   progressIndicator,   1)
#define ProgressIndicatorUpdateResponse_CALLBACK NULL
#define ProgressIndicatorUpdateResponse_DEFAULT NULL

#define UpdateResponse_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (update,uptimeUpdateResponse,update.uptimeUpdateResponse),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (update,progressIndicatorUpdateResponse,update.progressIndicatorUpdateResponse),   2)
#define UpdateResponse_CALLBACK NULL
#define UpdateResponse_DEFAULT NULL
#define UpdateResponse_update_uptimeUpdateResponse_MSGTYPE UptimeUpdateResponse
#define UpdateResponse_update_progressIndicatorUpdateResponse_MSGTYPE ProgressIndicatorUpdateResponse

#define PingRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   pingId,            1)
#define PingRequest_CALLBACK NULL
#define PingRequest_DEFAULT NULL

#define PingResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   pingId,            1) \
X(a, STATIC,   SINGULAR, UINT32,   uptime,            2)
#define PingResponse_CALLBACK NULL
#define PingResponse_DEFAULT NULL

#define MyAppCommand_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,helloQromaRequest,command.helloQromaRequest),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,mathRequest,command.mathRequest),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,setUpdateConfiguration,command.setUpdateConfiguration),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,setUpdateProgressIndicator,command.setUpdateProgressIndicator),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,pingRequest,command.pingRequest),   5)
#define MyAppCommand_CALLBACK NULL
#define MyAppCommand_DEFAULT NULL
#define MyAppCommand_command_helloQromaRequest_MSGTYPE HelloQromaRequest
#define MyAppCommand_command_mathRequest_MSGTYPE MathRequest
#define MyAppCommand_command_setUpdateConfiguration_MSGTYPE SetUpdateConfiguration
#define MyAppCommand_command_setUpdateProgressIndicator_MSGTYPE SetUpdateProgressIndicator
#define MyAppCommand_command_pingRequest_MSGTYPE PingRequest

#define MyAppResponse_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,helloQromaResponse,response.helloQromaResponse),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,mathResponse,response.mathResponse),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,setUpdateConfigurationResponse,response.setUpdateConfigurationResponse),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,setUpdateProgressIndicatorResponse,response.setUpdateProgressIndicatorResponse),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,pingResponse,response.pingResponse),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,update,response.update),   6)
#define MyAppResponse_CALLBACK NULL
#define MyAppResponse_DEFAULT NULL
#define MyAppResponse_response_helloQromaResponse_MSGTYPE HelloQromaResponse
#define MyAppResponse_response_mathResponse_MSGTYPE MathResponse
#define MyAppResponse_response_setUpdateConfigurationResponse_MSGTYPE SetUpdateConfigurationResponse
#define MyAppResponse_response_setUpdateProgressIndicatorResponse_MSGTYPE SetUpdateProgressIndicatorResponse
#define MyAppResponse_response_pingResponse_MSGTYPE PingResponse
#define MyAppResponse_response_update_MSGTYPE UpdateResponse

extern const pb_msgdesc_t HelloQromaRequest_msg;
extern const pb_msgdesc_t HelloQromaResponse_msg;
extern const pb_msgdesc_t MathRequest_msg;
extern const pb_msgdesc_t MathResult_Add_msg;
extern const pb_msgdesc_t MathResult_Subtract_msg;
extern const pb_msgdesc_t MathResult_AddAndSubtract_msg;
extern const pb_msgdesc_t MathResponse_msg;
extern const pb_msgdesc_t SetUpdateConfiguration_msg;
extern const pb_msgdesc_t SetUpdateConfigurationResponse_msg;
extern const pb_msgdesc_t SetUpdateProgressIndicator_msg;
extern const pb_msgdesc_t SetUpdateProgressIndicatorResponse_msg;
extern const pb_msgdesc_t UptimeUpdateResponse_msg;
extern const pb_msgdesc_t ProgressIndicatorUpdateResponse_msg;
extern const pb_msgdesc_t UpdateResponse_msg;
extern const pb_msgdesc_t PingRequest_msg;
extern const pb_msgdesc_t PingResponse_msg;
extern const pb_msgdesc_t MyAppCommand_msg;
extern const pb_msgdesc_t MyAppResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define HelloQromaRequest_fields &HelloQromaRequest_msg
#define HelloQromaResponse_fields &HelloQromaResponse_msg
#define MathRequest_fields &MathRequest_msg
#define MathResult_Add_fields &MathResult_Add_msg
#define MathResult_Subtract_fields &MathResult_Subtract_msg
#define MathResult_AddAndSubtract_fields &MathResult_AddAndSubtract_msg
#define MathResponse_fields &MathResponse_msg
#define SetUpdateConfiguration_fields &SetUpdateConfiguration_msg
#define SetUpdateConfigurationResponse_fields &SetUpdateConfigurationResponse_msg
#define SetUpdateProgressIndicator_fields &SetUpdateProgressIndicator_msg
#define SetUpdateProgressIndicatorResponse_fields &SetUpdateProgressIndicatorResponse_msg
#define UptimeUpdateResponse_fields &UptimeUpdateResponse_msg
#define ProgressIndicatorUpdateResponse_fields &ProgressIndicatorUpdateResponse_msg
#define UpdateResponse_fields &UpdateResponse_msg
#define PingRequest_fields &PingRequest_msg
#define PingResponse_fields &PingResponse_msg
#define MyAppCommand_fields &MyAppCommand_msg
#define MyAppResponse_fields &MyAppResponse_msg

/* Maximum encoded size of messages (where known) */
#define HelloQromaRequest_size                   21
#define HelloQromaResponse_size                  33
#define MathRequest_size                         14
#define MathResponse_size                        14
#define MathResult_AddAndSubtract_size           12
#define MathResult_Add_size                      6
#define MathResult_Subtract_size                 6
#define MyAppCommand_size                        23
#define MyAppResponse_size                       105
#define PingRequest_size                         6
#define PingResponse_size                        12
#define ProgressIndicatorUpdateResponse_size     51
#define SetUpdateConfigurationResponse_size      2
#define SetUpdateConfiguration_size              8
#define SetUpdateProgressIndicatorResponse_size  103
#define SetUpdateProgressIndicator_size          6
#define UpdateResponse_size                      53
#define UptimeUpdateResponse_size                6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
